name: Build and push to ECR

on:
  push:
    branches: ["main"]
permissions:
  id-token: write
  contents: read

jobs:
  build_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: "fs"
          severity: "HIGH,CRITICAL"
          #exit-code: "1"
          exit-code: "1"

      - name: Build Docker image
        run: docker build -t 600627356450.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest .

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 600627356450.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest
          format: "table"
          #exit-code: "1"
          exit-code: "0"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::600627356450:role/github-action-role
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2


      #- name: Push image to ECR
      #  run: echo "push

        
       


      #- name: tag the Docker image to be pushed to docker hub
      #  run: docker tag my-portfolio:latest 600627356450.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest

      #- name: Login to Docker Hub
       #with:
        #username: emmanuel2500
        #password: ${{ secrets.MYSECRETPORTFOLIOCI }}  

      #- name: push the Docker image to docker hub
       # run: docker push 600627356450.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest