name: Build and push to ECR
on:
  push:
    branches: ["main"]
permissions: # you give the workflow permission to request an OIDC token 
   #Without:# id-token: write# GitHub cannot create the OIDC token.
  id-token: write #This gives the workflow permission to request an OIDC token from GitHub
  contents: read #This gives the workflow permission to read(checkout reads the cloned repo) your repository contents.
#   For example:# - name: Checkout code#   uses: actions/checkout@v4# needs to download your source code:
# GitHub Repository -->GitHub Runner (ubuntu-latest) # Without:# contents: read# the checkout action cannot read your files.
jobs:
  build_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: "fs"
          severity: "HIGH,CRITICAL"
          #exit-code: "1"
          exit-code: "1"
      - name: Build Docker image
        run: docker build -t ${{secrets.AWS_ECR_REPO}}/my-portfolio:latest .

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{secrets.AWS_ECR_REPO}}/my-portfolio:latest
          format: "table"
          #exit-code: "1"
          exit-code: "0"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
      - name: Configure AWS credentials  # pushing image to ecr ,
      #we need to login. To login, we need to claim who we are(tokens) with role assuming,
      # then after get verified by aws, aws will give us the credentials that we will use to login from github to aws 



        uses: aws-actions/configure-aws-credentials@v4
#-------------------------------------------------------------------------------
#  when the workflow reaches  uses: aws-actions/configure-aws-credentials@v4 ,  |
# all of that OIDC token exchange and temporary credential creation happens:    |
#-------------------------------------------------------------------------------

#1.Create an  OIDC token from Github:
#-************************************
# #{
#   "iss": "https://token.actions.githubusercontent.com",
#   "sub": "repo:emmasine/my-portfolio:ref:refs/heads/main",
#   "aud": "sts.amazonaws.com",
#   "repository": "emmasine/my-portfolio",
#   "repository_owner": "emmasine",
#   "ref": "refs/heads/main",
#   "job_workflow_ref": "emmasine/my-portfolio/.github/workflows/deploy.yml@refs/heads/main"
# }   

# Meaning:

# iss → Who issued the token (GitHub)
# sub → Which repository is requesting access
# aud → Who should receive the token (AWS STS)
# ref → Which branch triggered it

# 2. AWS verifies the token:
#****************************

# Your IAM Role trust policy might say:

# {
#   "Effect": "Allow",
#   "Principal": {
#     "Federated": "arn:aws:iam::123456789012:oidc-provider/token.actions.githubusercontent.com"
#   },
#   "Action": "sts:AssumeRoleWithWebIdentity",
#   "Condition": {
#     "StringLike": {
#       "token.actions.githubusercontent.com:sub":
#       "repo:emmasine/my-portfolio:*"
#     }
#   }
# }

# AWS asks:

# "Does this token really come from GitHub, and is this repository allowed to assume this role?"

# If yes, AWS approves.

# 3. AWS returns temporary credentials:
#**************************************

# AWS STS gives GitHub Actions temporary credentials like:

# {
#   "AccessKeyId": "ASIA5Z7EXAMPLE123",
#   "SecretAccessKey": "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLE",
#   "SessionToken": "IQoJb3JpZ2luX2VjEEXAMPLE...",
#   "Expiration": "2026-07-12T22:30:00Z"
# }

# These are not your permanent AWS access keys.

# They are temporary.



# of course some ofthe  information from the GitHub OIDC token is compared against information that you already configured 
# in AWS IAM OIDC provider
#  and IAM role trust policy.
#============================================================================================

        # GitHub gets the OIDC token ✅
        # GitHub requests role assumption ✅
        # AWS STS verifies the token ✅
        # AWS returns temporary credentials ✅
        with:
          role-to-assume: ${{secrets.AWS_ROLE}}/github-action-role
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Push image to ECR # Build/push job → Configure AWS credentials + ECR login.
        run: docker push ${{secrets.AWS_ECR_REPO}}/my-portfolio:latest 
  Deploy-to_ecs:
    needs: build_scan # chaining.ie. deploy will run after build_scan finish
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials for us region audience
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: us-east-1
          role-to-assume: ${{secrets.AWS_ROLE}}/github-action-role
      #- name: Deploy to ecs # Deploy job → Configure AWS credentials only.
       # run: echo "Deploy to ecs"
      - name: Deploy to ecs
        run: |
          aws ecs update-service \
            --cluster dev-cluste \
            --service dev-portfo-service-mrdfvprw \
            --force-new-deployment

# or you can use the following(uses:)
          # - name: Deploy to ECS
          #   uses: aws-actions/amazon-ecs-deploy-task-definition@v2
          #   with:
          #     task-definition: dev-portfolio-td
          #     service: dev-portfo-service-mrdfvprw
          #     cluster: dev-cluste