name: Build and push to ECR
on:
  push:
    branches: ["main"]
permissions: # you give the workflow permission to request an OIDC token 
   #Without:# id-token: write# GitHub cannot create the OIDC token.
  id-token: write #This gives the workflow permission to request an OIDC token from GitHub
  contents: read #This gives the workflow permission to read(checkout reads the cloned repo) your repository contents.
#   For example:# - name: Checkout code#   uses: actions/checkout@v4# needs to download your source code:
# GitHub Repository -->GitHub Runner (ubuntu-latest) # Without:# contents: read# the checkout action cannot read your files.
jobs:
  build_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: "fs"
          severity: "HIGH,CRITICAL"
          #exit-code: "1"
          exit-code: "1"
      - name: Build Docker image
        run: docker build -t ${{secrets.AWS_ECR_REPO}}/my-portfolio:latest .

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{secrets.AWS_ECR_REPO}}/my-portfolio:latest
          format: "table"
          #exit-code: "1"
          exit-code: "0"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
      - name: Configure AWS credentials  # pushing image to ecr ,we need to login. To login, we need to claim who we are(credentilas) with role assuming
        uses: aws-actions/configure-aws-credentials@v4
        # GitHub gets the OIDC token ✅
        # GitHub requests role assumption ✅
        # AWS STS verifies the token ✅
        # AWS returns temporary credentials ✅
        with:
          role-to-assume: ${{secrets.AWS_ROLE}}/github-action-role
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Push image to ECR # Build/push job → Configure AWS credentials + ECR login.
        run: docker push ${{secrets.AWS_ECR_REPO}}/my-portfolio:latest 
  Deploy-to_ecs:
    needs: build_scan # chaining.ie. deploy will run after build_scan finish
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials for us region audience
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: us-east-1
          role-to-assume: ${{secrets.AWS_ROLE}}/github-action-role
      - name: Deploy to ecs # Deploy job → Configure AWS credentials only.
        run: echo "Deploy to ecs"
        